/**
 * Unit tests for `pruneVersions` in db/operations.ts
 *
 * Uses an in-memory libsql database with a hand-crafted versions table
 * that matches the schema generated by generateTables() for versioned collections.
 * No Docker required — all tests are pure in-memory SQLite.
 */
import { describe, it, expect, beforeEach } from "vitest";
import { createDatabase, type RunelayerDatabase } from "../init.js";
import { pruneVersions } from "../operations.js";
import type { CollectionConfig } from "../../schema/collections.js";
import { text } from "../../schema/fields.js";
import { applySchemaForTests } from "../../__testutils__/migrations.js";

// A minimal versioned collection — only needs to exist so the versions table is generated.
const VersionedArticles: CollectionConfig = {
  slug: "articles",
  fields: [{ name: "title", ...text({ required: true }) }],
  versions: true,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Insert a raw version row directly into the versions table, bypassing the query layer. */
async function insertVersionRow(
  rdb: RunelayerDatabase,
  opts: {
    id: string;
    parentId: string;
    version: number;
    status: "draft" | "published";
    createdAt: string;
  },
) {
  await rdb.client.execute({
    sql: `INSERT INTO "articles_versions" (id, _parentId, _version, _status, _snapshot, _createdBy, createdAt) VALUES (?, ?, ?, ?, ?, NULL, ?)`,
    args: [
      opts.id,
      opts.parentId,
      opts.version,
      opts.status,
      JSON.stringify({ title: `v${opts.version}` }),
      opts.createdAt,
    ],
  });
}

/** Returns all remaining version IDs for a given parentId, ordered by createdAt desc. */
async function fetchVersionIds(rdb: RunelayerDatabase, parentId: string): Promise<string[]> {
  const result = await rdb.client.execute({
    sql: `SELECT id FROM "articles_versions" WHERE _parentId = ? ORDER BY createdAt DESC`,
    args: [parentId],
  });
  return result.rows.map((r) => String((r as Record<string, unknown>).id));
}

async function countVersions(rdb: RunelayerDatabase, parentId: string): Promise<number> {
  const ids = await fetchVersionIds(rdb, parentId);
  return ids.length;
}

// Stable timestamps: t1 is oldest, t5 is newest
const t1 = "2026-01-01T00:00:01.000Z";
const t2 = "2026-01-01T00:00:02.000Z";
const t3 = "2026-01-01T00:00:03.000Z";
const t4 = "2026-01-01T00:00:04.000Z";
const t5 = "2026-01-01T00:00:05.000Z";

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe("pruneVersions", () => {
  let rdb: RunelayerDatabase;
  const versionsTable = () => rdb.tables["articles_versions"];
  const DOC_ID = "doc-1";

  beforeEach(async () => {
    rdb = createDatabase({ url: ":memory:", collections: [VersionedArticles] });
    await applySchemaForTests(rdb);
  });

  // -------------------------------------------------------------------------
  // Guard: maxPerDoc <= 0 means no pruning
  // -------------------------------------------------------------------------

  it("does nothing when maxPerDoc is 0", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 0);

    expect(await countVersions(rdb, DOC_ID)).toBe(5);
  });

  it("does nothing when maxPerDoc is negative", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, -1);

    expect(await countVersions(rdb, DOC_ID)).toBe(2);
  });

  // -------------------------------------------------------------------------
  // No-op: fewer rows than maxPerDoc
  // -------------------------------------------------------------------------

  it("does nothing when row count is less than maxPerDoc", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 5);

    expect(await countVersions(rdb, DOC_ID)).toBe(2);
  });

  it("does nothing when row count exactly equals maxPerDoc", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 3);

    expect(await countVersions(rdb, DOC_ID)).toBe(3);
  });

  // -------------------------------------------------------------------------
  // Basic: all-draft, evict oldest beyond budget
  // -------------------------------------------------------------------------

  /**
   * All-draft scenario: [v5, v4, v3, v2, v1], maxPerDoc=3.
   *
   * The early-exit guard fires only when all.length <= maxPerDoc (5 > 3, so pruning runs).
   *
   * Protected:
   *   - v5 (most-recent — always)
   *   - No published version, so only one protected item
   *
   * Budget counting (protected rows consume slots too):
   *   - v5 → kept=1 (protected)
   *   - v4 → kept=2
   *   - v3 → kept=3 (budget full)
   *   - v2 → evicted
   *   - v1 → evicted
   *
   * Survivors: v5, v4, v3 (3 rows — maxPerDoc is the total cap).
   */
  it("evicts oldest drafts when all versions are drafts (maxPerDoc=3, 5 rows → 3 remain)", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 3);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    // v5 (protected, kept=1), v4 (kept=2), v3 (kept=3), v2+v1 evicted
    expect(remaining).toHaveLength(3);
    expect(remaining).toContain("v5"); // most-recent — protected
    expect(remaining).toContain("v4"); // slot 2
    expect(remaining).toContain("v3"); // slot 3
    expect(remaining).not.toContain("v2"); // evicted
    expect(remaining).not.toContain("v1"); // evicted
  });

  // -------------------------------------------------------------------------
  // Protected: most-recent + latest-published are always kept
  // -------------------------------------------------------------------------

  /**
   * Scenario: [v5-draft, v4-draft, v3-published, v2-draft, v1-draft], maxPerDoc=2.
   *
   * Protected items (always kept even if over budget):
   *   - v5 (most-recent)
   *   - v3 (latest published)
   *
   * Budget counting (protected rows consume slots):
   *   - v5 → kept=1 (protected)
   *   - v4 → kept=2 (budget full)
   *   - v3 → kept=3 (protected — always kept even over budget)
   *   - v2 → evicted
   *   - v1 → evicted
   *
   * Total survivors: v5, v4, v3 (3 rows — protected can exceed maxPerDoc).
   */
  it("protects most-recent and latest-published, respects maxPerDoc as total cap", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 2);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toContain("v5"); // most-recent — always protected
    expect(remaining).toContain("v3"); // latest-published — always protected
    expect(remaining).toContain("v4"); // fills budget slot 2
    expect(remaining).not.toContain("v2"); // evicted
    expect(remaining).not.toContain("v1"); // evicted
  });

  /**
   * Edge: maxPerDoc=1 with a mix of draft and published.
   *
   * Protected items always kept even if over budget:
   *   - v5 (most-recent) → kept=1 (budget full)
   *   - v3 (latest-published) → kept=2 (over budget, but protected)
   *
   * Non-protected: v4, v2, v1 all evicted (budget already exhausted).
   *
   * Total: 2 rows (v5, v3).
   */
  it("keeps both protected items even when maxPerDoc=1", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toHaveLength(2);
    expect(remaining).toContain("v5"); // most-recent protected
    expect(remaining).toContain("v3"); // latest-published protected
    expect(remaining).not.toContain("v4"); // evicted — budget full
    expect(remaining).not.toContain("v2");
    expect(remaining).not.toContain("v1");
  });

  // -------------------------------------------------------------------------
  // Single published version: never deleted
  // -------------------------------------------------------------------------

  it("never deletes the single published version even when maxPerDoc=1", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "published",
      createdAt: t1,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    expect(await countVersions(rdb, DOC_ID)).toBe(1);
    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toContain("v1");
  });

  it("never deletes the single published version even under heavy pruning pressure", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "published",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    // With maxPerDoc=1, most-recent (v5) and latest-published (v1) are both protected.
    // Budget: v5 (kept=1, full), v4/v3/v2 evicted, v1 protected (kept=2, over budget).
    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toHaveLength(2);
    expect(remaining).toContain("v5"); // most-recent — always protected
    expect(remaining).toContain("v1"); // published — always protected
    expect(remaining).not.toContain("v4");
    expect(remaining).not.toContain("v3");
    expect(remaining).not.toContain("v2");
  });

  // -------------------------------------------------------------------------
  // Deduplication: most-recent IS the latest-published (same row)
  // -------------------------------------------------------------------------

  /**
   * When the most-recent version is also the only published version,
   * protectedIds = { v3 } (the same id added twice deduplicates to one entry).
   * Budget: v3 protected (kept=1, budget full), v2 and v1 evicted.
   * Total survivors: v3 only = 1.
   */
  it("deduplicates protected set when most-recent is also the latest-published", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published", // most-recent AND latest-published — same row
      createdAt: t3,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    // v3: protected (kept=1, budget full)
    // v2, v1: evicted
    expect(remaining).toContain("v3");
    expect(remaining).not.toContain("v2");
    expect(remaining).not.toContain("v1");
    expect(remaining).toHaveLength(1);
  });

  /**
   * Most-recent is published, maxPerDoc=2: v3 protected (kept=1), v2 (kept=2, budget full), v1 evicted.
   */
  it("evicts oldest when most-recent is published and total exceeds maxPerDoc", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published",
      createdAt: t3,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 2);

    // v3 protected (kept=1), v2 (kept=2), v1 evicted
    expect(await countVersions(rdb, DOC_ID)).toBe(2);
  });

  // -------------------------------------------------------------------------
  // Isolation: pruning for one doc doesn't touch other docs
  // -------------------------------------------------------------------------

  it("only prunes rows for the target document, leaves other docs untouched", async () => {
    const OTHER_ID = "doc-other";

    // Target doc: 5 drafts.
    // With maxPerDoc=3: t5 protected (kept=1), t4 (kept=2), t3 (kept=3, budget full), t2+t1 evicted. Total=3.
    await insertVersionRow(rdb, {
      id: "t1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "t2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "t3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "t4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "t5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    // Other doc: 2 rows — should not be touched
    await insertVersionRow(rdb, {
      id: "o1",
      parentId: OTHER_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "o2",
      parentId: OTHER_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 3);

    // t5 (protected, kept=1) + t4 (kept=2) + t3 (kept=3) = 3; t2+t1 evicted
    expect(await countVersions(rdb, DOC_ID)).toBe(3);
    // Other doc untouched
    expect(await countVersions(rdb, OTHER_ID)).toBe(2);
  });
});
