/**
 * Unit tests for `pruneVersions` in db/operations.ts
 *
 * Uses an in-memory libsql database with a hand-crafted versions table
 * that matches the schema generated by generateTables() for versioned collections.
 * No Docker required — all tests are pure in-memory SQLite.
 */
import { describe, it, expect, beforeEach } from "vitest";
import { createDatabase, type RunelayerDatabase } from "../init.js";
import { pruneVersions } from "../operations.js";
import type { CollectionConfig } from "../../schema/collections.js";
import { text } from "../../schema/fields.js";
import { applySchemaForTests } from "../../__testutils__/migrations.js";

// A minimal versioned collection — only needs to exist so the versions table is generated.
const VersionedArticles: CollectionConfig = {
  slug: "articles",
  fields: [{ name: "title", ...text({ required: true }) }],
  versions: true,
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Insert a raw version row directly into the versions table, bypassing the query layer. */
async function insertVersionRow(
  rdb: RunelayerDatabase,
  opts: {
    id: string;
    parentId: string;
    version: number;
    status: "draft" | "published";
    createdAt: string;
  },
) {
  await rdb.client.execute({
    sql: `INSERT INTO "articles_versions" (id, _parentId, _version, _status, _snapshot, _createdBy, createdAt) VALUES (?, ?, ?, ?, ?, NULL, ?)`,
    args: [
      opts.id,
      opts.parentId,
      opts.version,
      opts.status,
      JSON.stringify({ title: `v${opts.version}` }),
      opts.createdAt,
    ],
  });
}

/** Returns all remaining version IDs for a given parentId, ordered by createdAt desc. */
async function fetchVersionIds(rdb: RunelayerDatabase, parentId: string): Promise<string[]> {
  const result = await rdb.client.execute({
    sql: `SELECT id FROM "articles_versions" WHERE _parentId = ? ORDER BY createdAt DESC`,
    args: [parentId],
  });
  return result.rows.map((r) => String((r as Record<string, unknown>).id));
}

async function countVersions(rdb: RunelayerDatabase, parentId: string): Promise<number> {
  const ids = await fetchVersionIds(rdb, parentId);
  return ids.length;
}

// Stable timestamps: t1 is oldest, t5 is newest
const t1 = "2026-01-01T00:00:01.000Z";
const t2 = "2026-01-01T00:00:02.000Z";
const t3 = "2026-01-01T00:00:03.000Z";
const t4 = "2026-01-01T00:00:04.000Z";
const t5 = "2026-01-01T00:00:05.000Z";

// ---------------------------------------------------------------------------
// Test suite
// ---------------------------------------------------------------------------

describe("pruneVersions", () => {
  let rdb: RunelayerDatabase;
  const versionsTable = () => rdb.tables["articles_versions"];
  const DOC_ID = "doc-1";

  beforeEach(async () => {
    rdb = createDatabase({ url: ":memory:", collections: [VersionedArticles] });
    await applySchemaForTests(rdb);
  });

  // -------------------------------------------------------------------------
  // Guard: maxPerDoc <= 0 means no pruning
  // -------------------------------------------------------------------------

  it("does nothing when maxPerDoc is 0", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 0);

    expect(await countVersions(rdb, DOC_ID)).toBe(5);
  });

  it("does nothing when maxPerDoc is negative", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, -1);

    expect(await countVersions(rdb, DOC_ID)).toBe(2);
  });

  // -------------------------------------------------------------------------
  // No-op: fewer rows than maxPerDoc
  // -------------------------------------------------------------------------

  it("does nothing when row count is less than maxPerDoc", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 5);

    expect(await countVersions(rdb, DOC_ID)).toBe(2);
  });

  it("does nothing when row count exactly equals maxPerDoc", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 3);

    expect(await countVersions(rdb, DOC_ID)).toBe(3);
  });

  // -------------------------------------------------------------------------
  // Basic: all-draft, evict oldest beyond budget
  // -------------------------------------------------------------------------

  /**
   * All-draft scenario: [v5, v4, v3, v2, v1], maxPerDoc=3.
   *
   * The early-exit guard fires only when all.length <= maxPerDoc (5 > 3, so pruning runs).
   *
   * Protected:
   *   - v5 (most-recent — always)
   *   - No published version, so only one protected item
   *
   * Non-protected budget = 3:
   *   - v4 → slot 1
   *   - v3 → slot 2
   *   - v2 → slot 3
   *   - v1 → evicted (budget exhausted)
   *
   * Survivors: v5, v4, v3, v2 (4 rows total — protected rows do not consume budget).
   */
  it("evicts oldest draft when all versions are drafts (maxPerDoc=3, 5 rows → 4 remain)", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 3);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    // v5 (protected), v4/v3/v2 (consume budget), v1 (evicted)
    expect(remaining).toHaveLength(4);
    expect(remaining).toContain("v5"); // most-recent — protected
    expect(remaining).toContain("v4"); // slot 1
    expect(remaining).toContain("v3"); // slot 2
    expect(remaining).toContain("v2"); // slot 3
    expect(remaining).not.toContain("v1"); // evicted
  });

  // -------------------------------------------------------------------------
  // Protected: most-recent + latest-published are always kept
  // -------------------------------------------------------------------------

  /**
   * Scenario: [v5-draft, v4-draft, v3-published, v2-draft, v1-draft], maxPerDoc=2.
   *
   * Protected items:
   *   - v5 (most-recent, always kept regardless)
   *   - v3 (latest published, always kept regardless)
   *
   * Non-protected budget is maxPerDoc=2 slots:
   *   - v4 gets slot 1
   *   - v2 gets slot 2
   *   - v1 is evicted
   *
   * Total survivors: v5, v4, v3, v2 (4 rows).
   */
  it("protects most-recent and latest-published, keeps 2 non-protected with maxPerDoc=2", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 2);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toContain("v5"); // most-recent — always protected
    expect(remaining).toContain("v3"); // latest-published — always protected
    expect(remaining).toContain("v4"); // non-protected slot 1
    expect(remaining).toContain("v2"); // non-protected slot 2
    expect(remaining).not.toContain("v1"); // evicted
  });

  /**
   * Edge: maxPerDoc=1 with a mix of draft and published.
   *
   * Minimum guaranteed survivors: most-recent (v5) + latest-published (v3).
   * Non-protected budget = 1: v4 keeps the budget.
   * v2 and v1 are evicted.
   *
   * Total: 3 rows (v5, v4, v3).
   */
  it("keeps both protected items even when maxPerDoc=1", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toContain("v5"); // most-recent protected
    expect(remaining).toContain("v3"); // latest-published protected
    expect(remaining).not.toContain("v1");
    expect(remaining).not.toContain("v2");
  });

  // -------------------------------------------------------------------------
  // Single published version: never deleted
  // -------------------------------------------------------------------------

  it("never deletes the single published version even when maxPerDoc=1", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "published",
      createdAt: t1,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    expect(await countVersions(rdb, DOC_ID)).toBe(1);
    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toContain("v1");
  });

  it("never deletes the single published version even under heavy pruning pressure", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "published",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "v4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "v5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    // With maxPerDoc=1, most-recent (v5) and latest-published (v1) are both protected.
    // Non-protected budget = 1: v4 keeps the slot. v3 and v2 are evicted.
    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    expect(remaining).toContain("v1"); // published — always protected
    expect(remaining).toContain("v5"); // most-recent — always protected
    expect(remaining).not.toContain("v3");
    expect(remaining).not.toContain("v2");
  });

  // -------------------------------------------------------------------------
  // Deduplication: most-recent IS the latest-published (same row)
  // -------------------------------------------------------------------------

  /**
   * When the most-recent version is also the only published version,
   * protectedIds = { v3 } (the same id added twice deduplicates to one entry).
   * Non-protected budget = maxPerDoc. With maxPerDoc=1: v2 gets slot 1, v1 evicted.
   * Total survivors: v3 + v2 = 2.
   */
  it("deduplicates protected set when most-recent is also the latest-published", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published", // most-recent AND latest-published — same row
      createdAt: t3,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 1);

    const remaining = await fetchVersionIds(rdb, DOC_ID);
    // v3: both protected roles → kept (counts as ONE protected item, not two)
    // v2: non-protected slot 1 → kept
    // v1: budget exhausted → evicted
    expect(remaining).toContain("v3");
    expect(remaining).toContain("v2");
    expect(remaining).not.toContain("v1");
    expect(remaining).toHaveLength(2);
  });

  /**
   * Most-recent is published, maxPerDoc=2: budget fills v2 and v1 — nothing evicted.
   */
  it("does not evict when most-recent is published and total fits within maxPerDoc + 1 protected", async () => {
    await insertVersionRow(rdb, {
      id: "v1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "v2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "v3",
      parentId: DOC_ID,
      version: 3,
      status: "published",
      createdAt: t3,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 2);

    // v3 protected, v2 slot 1, v1 slot 2 — all kept
    expect(await countVersions(rdb, DOC_ID)).toBe(3);
  });

  // -------------------------------------------------------------------------
  // Isolation: pruning for one doc doesn't touch other docs
  // -------------------------------------------------------------------------

  it("only prunes rows for the target document, leaves other docs untouched", async () => {
    const OTHER_ID = "doc-other";

    // Target doc: 5 drafts.
    // With maxPerDoc=3: v5 protected (most-recent), budget 3 → v4/v3/v2 kept, v1 evicted. Total=4.
    await insertVersionRow(rdb, {
      id: "t1",
      parentId: DOC_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "t2",
      parentId: DOC_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });
    await insertVersionRow(rdb, {
      id: "t3",
      parentId: DOC_ID,
      version: 3,
      status: "draft",
      createdAt: t3,
    });
    await insertVersionRow(rdb, {
      id: "t4",
      parentId: DOC_ID,
      version: 4,
      status: "draft",
      createdAt: t4,
    });
    await insertVersionRow(rdb, {
      id: "t5",
      parentId: DOC_ID,
      version: 5,
      status: "draft",
      createdAt: t5,
    });

    // Other doc: 2 rows — should not be touched
    await insertVersionRow(rdb, {
      id: "o1",
      parentId: OTHER_ID,
      version: 1,
      status: "draft",
      createdAt: t1,
    });
    await insertVersionRow(rdb, {
      id: "o2",
      parentId: OTHER_ID,
      version: 2,
      status: "draft",
      createdAt: t2,
    });

    await pruneVersions(rdb.db, versionsTable(), DOC_ID, 3);

    // v5 (protected) + v4/v3/v2 (budget) = 4; v1 evicted
    expect(await countVersions(rdb, DOC_ID)).toBe(4);
    // Other doc untouched
    expect(await countVersions(rdb, OTHER_ID)).toBe(2);
  });
});
